### ISSUE TITLE
Satin column crash

### ISSUE THREAD

**Issue by lexelby** [lexelby/inkstitch#168]
From #167 

```Traceback (most recent call last):
  File "embroider.py", line 108, in <module>
  File "inkscape-0.92.2/share/extensions/inkex.py", line 283, in affect
    errormsg(_("No matching node for expression: %s") % path)
  File "embroider.py", line 97, in effect
    
  File "inkstitch/extensions.py", line 195, in elements_to_patches
  File "inkstitch/elements/element.py", line 244, in embroider
  File "inkstitch/elements/satin_column.py", line 401, in to_patches
  File "inkstitch/elements/satin_column.py", line 370, in do_satin
  File "inkstitch/elements/satin_column.py", line 254, in walk_paths
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "inkstitch/elements/satin_column.py", line 101, in flattened_beziers
  File "inkstitch/elements/satin_column.py", line 128, in flatten_beziers_with_rungs
  File "site-packages/shapely/ops.py", line 464, in split
ValueError: Splitting a LineString with a GeometryCollection is not supported
[9557] Failed to execute script embroider
```

This is probably enough to figure out the bug.

**Comment by lexelby** [comment]
Problem occurs when `embroider_satin_column` is set for a path with only one subpath.
