### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by danielkschneider** [lexelby/inkstitch#194]
Not a showstopper. I got this with the attached prado-love-2.svg
[love.zip](https://github.com/lexelby/inkstitch/files/2084808/love.zip)

It "simply" is related to the size of the design (only 13mm wide)

The included prado-love-3.svg is bigger and just does fine.

Version: Inkscape 0.92.3 Ubuntu 16LTS
               InkStitch 1.8.2 (of June 8 2018)

- greetings ! Daniel
PS: Of course, I was just distracted and forgot to make the thing bigger. The original is also in the zip and from here: https://thenounproject.com/search/?q=love&i=15070

Traceback (most recent call last):
  File "inkstitch.py", line 20, in <module>
    if script_name.endswith('.py'):
  File "inkscape-0.92.2/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/embroider.py", line 84, in effect
  File "lib/extensions/base.py", line 196, in elements_to_patches
  File "lib/elements/element.py", line 257, in embroider
  File "lib/elements/auto_fill.py", line 112, in to_patches
  File "lib/elements/auto_fill.py", line 97, in underlay_shape
  File "lib/elements/auto_fill.py", line 93, in shrink_or_grow_shape
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/elements/fill.py", line 65, in shape
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/elements/fill.py", line 59, in paths
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/elements/element.py", line 214, in parse_path
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/svg/units.py", line 89, in get_viewbox_transform
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/svg/units.py", line 81, in get_doc_size
  File "lib/svg/units.py", line 50, in convert_length
  File "lib/svg/units.py", line 20, in parse_length_with_units
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by lexelby** [comment]
Looks like another example of this issue: https://github.com/lexelby/inkstitch/issues/156#issuecomment-383948376

It doesn't have anything to do with the size of the document.  Ink/Stitch doesn't handle SVGs that don't have a width or height specified in the `<svg>` tag.  Easy fix -- should be ready shortly.

**Comment by lexelby** [comment]
There's actually another bug: for `prado-love.svg`, Ink/Stitch claims "no embroiderable paths found", but I can plainly see them right there.  It turns out that the paths in that SVG don't have a fill or a stroke declared.  Ink/Stitch interpreted that to mean that the objects had neither a fill nor a stroke, but the SVG spec says that the default fill is black.
