### ISSUE TITLE
Support document size specified in points

### ISSUE THREAD

**Issue by exussum12** [lexelby/inkstitch#84]
If the document's dimensions are specified in points (or any unit other than inches, centimeters, millimeters, or pixels) then Inkstitch crashes.

original description follows:

----------------------------------------

Not sure what I am missing 

Traceback (most recent call last):
  File "embroider.py", line 1770, in <module>
    
  File "inkex.py", line 283, in affect
    self.effect()
  File "embroider.py", line 1752, in effect
    
  File "embroider.py", line 1662, in elements_to_patches
    
  File "inkstitch.py", line 343, in embroider
  File "embroider.py", line 874, in to_patches
    
  File "embroider.py", line 842, in do_auto_fill
    
  File "embroider.py", line 150, in intersect_region_with_grating
    
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "embroider.py", line 92, in shape
    
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "embroider.py", line 86, in paths
    
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "inkstitch.py", line 293, in parse_path
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "inkstitch.py", line 125, in get_viewbox_transform
  File "inkstitch.py", line 118, in convert_length
ValueError: Unknown unit: pt
[12001] Failed to execute script embroider

using latest version.

Thanks for looking :)

**Comment by lexelby** [comment]
Hi!  Would you be willing to post your SVG?  I think I know what's going on here but I'm not certain without seeing the svg.

**Comment by exussum12** [comment]
Sure its http://thephantoms.co.uk/phorum/styles/prosilver/imageset/FlintshirePhantoms.svg  Thanks for quick reply

**Comment by exussum12** [comment]
Going to dst format not sure if that matters

**Comment by lexelby** [comment]
Here's what's going on: your document's size is specified in units of "points" (1/72 of an inch, I think?).  Inkstitch doesn't know how to convert that to inches yet, so it gets confused and crashes.  It should be a fairly easy fix in the code.

To work around the issue, you can change your document's size to be in a different unit.  Go to File -> Document Properties, and change the "unit" dropdown to inches, mm, cm, or pixels.  Just to be clear, this is a workaround, and I consider it a bug that Inkstitch doesn't support points.

BTW, welcome to the project, and I hope you enjoy Inkstitch :)

**Comment by exussum12** [comment]
Brilliant that worked, Thanks
