### ISSUE TITLE
Running embroider a second time throws a error!

### ISSUE THREAD

**Issue by X3msnake** [lexelby/inkstitch#88]
As stated on https://github.com/lexelby/inkstitch/pull/83#

This error occurs in all the versions I have tested VM 32/64bit and Windows 

```
[5684] Failed to execute script embroider
Traceback (most recent call last):
  File "embroider.py", line 1774, in <module>
  File "inkscape-0.92.2\share\extensions\inkex.py", line 283, in affect
  File "embroider.py", line 1756, in effect
  File "embroider.py", line 1662, in elements_to_patches
  File "inkstitch.py", line 343, in embroider
  File "embroider.py", line 1452, in to_patches
  File "embroider.py", line 1445, in stitches
  File "site-packages\backports\functools_lru_cache.py", line 113, in wrapper
  File "embroider.py", line 1427, in csp
  File "site-packages\backports\functools_lru_cache.py", line 113, in wrapper
  File "inkstitch.py", line 284, in parse_path
  File "embroider.py", line 1420, in path
  File "embroider.py", line 1408, in points
ValueError: could not convert string to float:
```

This should either throw a readable error like;
  Please delete embroider layer before continuing

Or Ideally;
 it should detect that the layer is already created, delete that layer and process the hidden ones

**Comment by X3msnake** [comment]
@lexelby you can close this it is adressed in the latest rlease
